import React, { useState, useId } from 'react';
import { Helmet } from 'react-helmet-async';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Sparkles, 
  Cpu, 
  Compass, 
  Shield, 
  Lock, 
  ArrowRight, 
  RotateCcw, 
  Share2, 
  CheckCircle2, 
  AlertTriangle,
  ExternalLink,
  ChevronRight
} from 'lucide-react';
import { Link } from 'react-router-dom';

interface QuestionCategory {
  id: 'delegation' | 'description' | 'discernment' | 'diligence';
  num: number;
  title: string;
  subtitle: string;
  themeColor: string;
  accentBg: string;
  icon: typeof Cpu;
  questions: string[];
}

const CATEGORIES: QuestionCategory[] = [
  {
    id: 'delegation',
    num: 1,
    title: 'Delegation (Architecting Labor)',
    subtitle: 'How strategically do you divide labor between human intellect and machine computation?',
    themeColor: '#EA580C',
    accentBg: 'rgba(234, 88, 12, 0.15)',
    icon: Cpu,
    questions: [
      "I clearly define my project's strategic goal, target audience, and cultural context BEFORE opening an AI tool.",
      "I intentionally reserve tasks requiring cultural empathy, ethical judgment, and final strategy for myself.",
      "I actively delegate high-volume ideation, data synthesis, and structural formatting to the AI.",
      "I evaluate the specific capabilities and limits (e.g., context windows, knowledge cutoffs) of an AI model before using it.",
      "I view AI as an interactive cognitive partner rather than a passive tool to 'just do the work for me.'"
    ]
  },
  {
    id: 'description',
    num: 2,
    title: 'Description (Context Engineering)',
    subtitle: 'How effectively do you define the product, process, and performance for the AI?',
    themeColor: '#FFE066',
    accentBg: 'rgba(255, 224, 102, 0.15)',
    icon: Compass,
    questions: [
      "I explicitly define the desired format, length, and cultural tone (The Product) in my initial prompts.",
      "I instruct the AI on the specific steps or logic pathways it should use to complete the task (The Process).",
      "I assign the AI a specific persona, role, or constraint (e.g., 'Act as a critical editor') to shape its behavior.",
      "I provide the AI with extensive external context (documents, real-world data) rather than relying on its default knowledge.",
      "I command the AI to ask me clarifying questions before it begins generating an output."
    ]
  },
  {
    id: 'discernment',
    num: 3,
    title: 'Discernment (The Human Defense)',
    subtitle: 'How rigorously do you scrutinize outputs to prevent automation bias and cultural erasure?',
    themeColor: '#25D366',
    accentBg: 'rgba(37, 211, 102, 0.15)',
    icon: Shield,
    questions: [
      "I actively scrutinize AI outputs for cultural homogenization, Western bias, or inaccurate African stereotypes.",
      "I independently double-check factual claims, statistics, and legal precedents generated by the AI.",
      "I evaluate the underlying logic or reasoning the AI used to arrive at its output, not just the final text.",
      "I refuse to accept the 'polished first draft' and instead push the AI through multiple revision iterations.",
      "I remain highly skeptical of outputs that look aesthetically perfect but lack strategic or emotional depth."
    ]
  },
  {
    id: 'diligence',
    num: 4,
    title: 'Diligence (Accountability & IP)',
    subtitle: 'How ethically and legally responsible are you with deployed AI assets?',
    themeColor: '#A78BFA',
    accentBg: 'rgba(167, 139, 250, 0.15)',
    icon: Lock,
    questions: [
      "I verify the data privacy policies of an AI platform before uploading sensitive client or cultural data.",
      "I am transparent with clients, collaborators, or my audience about the extent of AI used in my creative work.",
      "I inject substantial original human creativity into AI drafts to ensure the final asset is legally defensible (copyrightable).",
      "I take 100% personal and legal responsibility for any errors, biases, or flaws in the final deployed product.",
      "I actively advocate for the protection of indigenous data and intellectual property in my workflows."
    ]
  }
];

const SCALES = [
  { val: 1, label: 'Never', short: '1' },
  { val: 2, label: 'Rarely', short: '2' },
  { val: 3, label: 'Sometimes', short: '3' },
  { val: 4, label: 'Often', short: '4' },
  { val: 5, label: 'Always', short: '5' },
];

const FEEDBACK: Record<string, string> = {
  delegation: "You possess a strong strategic mind, knowing exactly when to utilize machine computation versus human intuition.",
  description: "You excel at Context Engineering, successfully shaping AI behavior, process, and product parameters to bypass generic outputs.",
  discernment: "You have a powerful critical eye, successfully defending against algorithmic hallucinations, bias, and the 'polished output problem'.",
  diligence: "You operate with world-class ethical and legal accountability, ensuring your IP is defensible and your data practices are secure."
};

const WARNINGS: Record<string, string> = {
  delegation: "You need to better define your strategic goals and separate your tasks. Stop treating AI like a search engine and start treating it like a specialized cognitive team member.",
  description: "You must stop writing basic 'prompts' and start engineering 'context'. Define the format, persona, and process limitations clearly to get world-class outputs.",
  discernment: "You are highly susceptible to automation bias. You must aggressively scrutinize AI outputs for factual errors, logical leaps, and cultural erasure before using them.",
  diligence: "Your lack of accountability exposes you to severe legal and reputational risks. You must prioritize data privacy, transparent disclosure, and human IP injection."
};

interface RadarChartProps {
  scores: { delegation: number; description: number; discernment: number; diligence: number };
}

function RadarChart({ scores }: RadarChartProps) {
  const size = 300;
  const center = size / 2;
  const maxRadius = 95;
  const maxScore = 25;

  // Axis coordinates (Angles: Top, Right, Bottom, Left)
  // Delegation (Top): angle -90deg
  // Description (Right): angle 0deg
  // Discernment (Bottom): angle 90deg
  // Diligence (Left): angle 180deg
  const rDelegation = (scores.delegation / maxScore) * maxRadius;
  const rDescription = (scores.description / maxScore) * maxRadius;
  const rDiscernment = (scores.discernment / maxScore) * maxRadius;
  const rDiligence = (scores.diligence / maxScore) * maxRadius;

  const points = [
    `${center},${center - rDelegation}`,
    `${center + rDescription},${center}`,
    `${center},${center + rDiscernment}`,
    `${center - rDiligence},${center}`
  ].join(' ');

  const gridLevels = [0.25, 0.5, 0.75, 1.0];

  return (
    <div className="relative w-full max-w-[300px] aspect-square mx-auto flex items-center justify-center">
      <svg viewBox={`0 0 ${size} ${size}`} className="w-full h-full overflow-visible">
        <defs>
          <radialGradient id="radarRadialGlow" cx="50%" cy="50%" r="50%">
            <stop offset="0%" stopColor="#EA580C" stopOpacity="0.45" />
            <stop offset="70%" stopColor="#F59E0B" stopOpacity="0.25" />
            <stop offset="100%" stopColor="#EA580C" stopOpacity="0" />
          </radialGradient>
          <filter id="radarGlow" x="-20%" y="-20%" width="140%" height="140%">
            <feGaussianBlur stdDeviation="4" result="blur" />
            <feMerge>
              <feMergeNode in="blur" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
        </defs>

        {/* Concentric Grid Diamond Rings */}
        {gridLevels.map((lvl, idx) => {
          const r = lvl * maxRadius;
          const gridPoints = [
            `${center},${center - r}`,
            `${center + r},${center}`,
            `${center},${center + r}`,
            `${center - r},${center}`
          ].join(' ');
          return (
            <polygon
              key={idx}
              points={gridPoints}
              fill="none"
              stroke="rgba(255, 255, 255, 0.12)"
              strokeWidth="1"
              strokeDasharray={idx < 3 ? '3 3' : 'none'}
            />
          );
        })}

        {/* Crosshair Axes */}
        <line x1={center} y1={center - maxRadius} x2={center} y2={center + maxRadius} stroke="rgba(255, 255, 255, 0.16)" strokeWidth="1" />
        <line x1={center - maxRadius} y1={center} x2={center + maxRadius} y2={center} stroke="rgba(255, 255, 255, 0.16)" strokeWidth="1" />

        {/* Active Score Polygon Area */}
        <polygon
          points={points}
          fill="url(#radarRadialGlow)"
          stroke="#EA580C"
          strokeWidth="2.5"
          filter="url(#radarGlow)"
          className="transition-all duration-700 ease-out"
        />

        {/* Vertices Dots */}
        <circle cx={center} cy={center - rDelegation} r="4.5" fill="#FFE066" stroke="#EA580C" strokeWidth="2" />
        <circle cx={center + rDescription} cy={center} r="4.5" fill="#FFE066" stroke="#EA580C" strokeWidth="2" />
        <circle cx={center} cy={center + rDiscernment} r="4.5" fill="#FFE066" stroke="#EA580C" strokeWidth="2" />
        <circle cx={center - rDiligence} cy={center} r="4.5" fill="#FFE066" stroke="#EA580C" strokeWidth="2" />

        {/* Axis Labels */}
        <text x={center} y={center - maxRadius - 12} textAnchor="middle" fill="#FFFFFF" fontSize="11" fontFamily="'Plus Jakarta Sans', sans-serif" fontWeight="bold">
          DELEGATION ({scores.delegation})
        </text>
        <text x={center + maxRadius + 10} y={center + 4} textAnchor="start" fill="#FFFFFF" fontSize="11" fontFamily="'Plus Jakarta Sans', sans-serif" fontWeight="bold">
          DESCRIPTION ({scores.description})
        </text>
        <text x={center} y={center + maxRadius + 20} textAnchor="middle" fill="#FFFFFF" fontSize="11" fontFamily="'Plus Jakarta Sans', sans-serif" fontWeight="bold">
          DISCERNMENT ({scores.discernment})
        </text>
        <text x={center - maxRadius - 10} y={center + 4} textAnchor="end" fill="#FFFFFF" fontSize="11" fontFamily="'Plus Jakarta Sans', sans-serif" fontWeight="bold">
          DILIGENCE ({scores.diligence})
        </text>
      </svg>
    </div>
  );
}

export default function AIAudit() {
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [isCalculated, setIsCalculated] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);

  const totalQuestions = 20;
  const answeredCount = Object.keys(answers).length;
  const isComplete = answeredCount === totalQuestions;

  const handleSelectAnswer = (category: string, qIndex: number, val: number) => {
    const key = `${category}_${qIndex}`;
    setAnswers((prev) => ({ ...prev, [key]: val }));
  };

  const handleCalculate = () => {
    if (!isComplete) return;
    setIsCalculated(true);
    // Smooth scroll to top of dashboard
    setTimeout(() => {
      window.scrollTo({ top: 180, behavior: 'smooth' });
    }, 100);
  };

  const handleReset = () => {
    setAnswers({});
    setIsCalculated(false);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  // Compute Scores
  const scores = { delegation: 0, description: 0, discernment: 0, diligence: 0 };
  let totalScore = 0;

  CATEGORIES.forEach((cat) => {
    cat.questions.forEach((_, qIndex) => {
      const val = answers[`${cat.id}_${qIndex}`] || 0;
      scores[cat.id] += val;
    });
    totalScore += scores[cat.id];
  });

  // Determine Archetype
  let archetypeTitle = '';
  let archetypeTag = '';
  let archetypeDesc = '';
  let archetypeColor = '';

  if (totalScore <= 40) {
    archetypeTitle = 'The Commodity Laborer';
    archetypeTag = 'High Risk of Automation';
    archetypeColor = 'from-red-500 to-orange-600 text-red-400';
    archetypeDesc = 'High Risk. You are using AI passively or not at all. Competing strictly on basic execution and speed makes your career highly vulnerable to automation displacement by autonomous agentic workflows.';
  } else if (totalScore <= 65) {
    archetypeTitle = 'The Prompt Jockey';
    archetypeTag = 'Moderate Vulnerability';
    archetypeColor = 'from-orange-500 to-amber-500 text-orange-400';
    archetypeDesc = 'Moderate Risk. You use AI for speed and basic ideation, but you lack strategic depth and cultural defense. You are vulnerable to the "Polished Output Problem", often accepting drafts without rigorous discernment.';
  } else if (totalScore <= 85) {
    archetypeTitle = 'The AI-Augmented Creative';
    archetypeTag = 'Low Risk • High Leverage';
    archetypeColor = 'from-emerald-400 to-teal-500 text-emerald-400';
    archetypeDesc = 'Low Risk. You have established a strong cognitive partnership with AI. You iterate well, engineer solid context, and maintain a robust baseline of human defense and ethical diligence.';
  } else {
    archetypeTitle = 'The Systems Architect';
    archetypeTag = 'Future-Proofed • Sovereign Pioneer';
    archetypeColor = 'from-amber-400 via-[var(--color-cmf-gold)] to-orange-500 text-[var(--color-cmf-gold)]';
    archetypeDesc = 'Future-Proofed. You are a master orchestrator. You dictate process, rigorously defend cultural authenticity, and take absolute legal ownership of your IP. You are indispensable to the global creative economy.';
  }

  // Sorted Highest and Lowest
  const categoryKeys = Object.keys(scores) as (keyof typeof scores)[];
  const sortedCategories = [...categoryKeys].sort((a, b) => scores[b] - scores[a]);
  const highestCategory = sortedCategories[0];
  const lowestCategory = sortedCategories[sortedCategories.length - 1];

  const handleShare = () => {
    const text = `I just took the 4D AI Fluency Audit on Creative Minds' Forum and scored ${totalScore}/100 — diagnosed as "${archetypeTitle}". Discover where your creative career stands in the AI revolution: ${window.location.href}`;
    if (navigator.share) {
      navigator.share({ title: "My 4D AI Fluency Audit Score", text, url: window.location.href });
    } else {
      navigator.clipboard.writeText(text);
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2500);
    }
  };

  return (
    <>
      <Helmet>
        <title>The 4D AI Fluency Audit | Creative Minds' Forum</title>
        <meta
          name="description"
          content="Assess your strategic positioning in the creative gig economy. Answer 20 questions based on the 4D AI Fluency framework to discover if you are a Commodity Laborer or a Systems Architect."
        />
        <meta property="og:title" content="The 4D AI Fluency Audit | Creative Minds' Forum" />
        <meta
          property="og:description"
          content="Calculate your creative career vulnerability score across Delegation, Description, Discernment, and Diligence."
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://creativemindsforum.com/ai-audit" />
      </Helmet>

      <main className="min-h-screen bg-[#07070A] text-white pt-24 sm:pt-32 pb-32 px-4 sm:px-6 lg:px-8 selection:bg-orange-500/30 selection:text-white relative overflow-hidden">
        
        {/* ── Ambient Background Lighting ── */}
        <div className="absolute top-10 left-1/2 -translate-x-1/2 w-[700px] h-[550px] bg-gradient-to-b from-orange-500/15 via-[var(--color-cmf-gold)]/5 to-transparent blur-[140px] pointer-events-none -z-10" />
        <div className="absolute top-[40%] right-[-10%] w-[500px] h-[600px] bg-indigo-600/[0.05] blur-[160px] pointer-events-none -z-10" />
        <div className="absolute bottom-[20%] left-[-10%] w-[500px] h-[500px] bg-emerald-500/[0.04] blur-[160px] pointer-events-none -z-10" />

        {/* ── Background Grid Pattern ── */}
        <div 
          className="absolute inset-0 opacity-[0.03] pointer-events-none -z-10"
          style={{
            backgroundImage: `radial-gradient(circle at 1px 1px, #FFFFFF 1px, transparent 0)`,
            backgroundSize: '40px 40px',
          }}
        />

        <div className="max-w-4xl mx-auto">

          {/* ═════════════════════════════════════════════════════════════════
              PAGE HEADER
              ═════════════════════════════════════════════════════════════════ */}
          <div className="text-center max-w-3xl mx-auto mb-12 sm:mb-16">
            
            {/* Top Pill */}
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white/[0.04] border border-white/10 backdrop-blur-md text-xs font-mono text-gray-300 mb-5 shadow-xs"
            >
              <span className="w-2 h-2 rounded-full bg-orange-500 animate-pulse shadow-[0_0_8px_#ea580c]" />
              <span className="text-orange-400 font-semibold uppercase tracking-wider">Creatives Connect</span>
              <span className="text-gray-500">•</span>
              <span className="text-gray-400">4D AI Fluency Framework</span>
            </motion.div>

            {/* Title */}
            <motion.h1
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-extrabold text-white tracking-tight leading-[1.12]"
            >
              The 4D AI Fluency{' '}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 via-[var(--color-cmf-gold)] to-orange-500">
                Audit
              </span>
            </motion.h1>

            {/* Subtitle */}
            <motion.p
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="mt-4 text-sm sm:text-base md:text-lg text-gray-300 font-light leading-relaxed max-w-2xl mx-auto"
            >
              Discover your vulnerability to the gig economy polarization. Answer the 20 questions below to calculate your strategic career positioning and find out if you are a <strong className="text-white font-medium">Commodity Laborer</strong> or a <strong className="text-[var(--color-cmf-gold)] font-medium">Systems Architect</strong>.
            </motion.p>

            {/* Academic & Theoretical Attribution */}
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.3 }}
              className="mt-4 text-xs font-serif italic text-gray-500 border-t border-white/[0.08] pt-3 max-w-lg mx-auto"
            >
              *Based on the foundational AI Fluency 4D Framework developed by Rick Dakan, Joseph Feller, and Anthropic.
            </motion.p>
          </div>

          {/* ═════════════════════════════════════════════════════════════════
              DIAGNOSTIC RESULTS DASHBOARD (Rendered once calculated)
              ═════════════════════════════════════════════════════════════════ */}
          <AnimatePresence>
            {isCalculated && (
              <motion.div
                initial={{ opacity: 0, scale: 0.96, y: 30 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.96, y: -20 }}
                transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
                className="mb-16 space-y-8"
              >
                {/* Hero Results Card */}
                <div className="relative rounded-3xl p-6 sm:p-10 bg-gradient-to-br from-[#12121A] to-[#0A0A10] border border-orange-500/40 shadow-[0_25px_80px_rgba(0,0,0,0.95),0_0_50px_rgba(234,88,12,0.2)] overflow-hidden">
                  
                  {/* Decorative Radial Accent */}
                  <div className="absolute top-0 right-0 w-80 h-80 bg-orange-500/10 blur-[100px] pointer-events-none" />

                  <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-center relative z-10">
                    
                    {/* Diagnosis Text */}
                    <div className="md:col-span-7 space-y-4">
                      <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/[0.06] border border-white/10 text-xs font-mono font-semibold uppercase tracking-wider text-orange-400">
                        <Sparkles className="w-3.5 h-3.5" />
                        <span>Your Career Diagnosis</span>
                      </div>

                      <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight leading-tight">
                        {archetypeTitle}
                      </h2>

                      <span className={`inline-block text-xs font-mono font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-md bg-white/[0.05] border border-white/10 ${archetypeColor}`}>
                        {archetypeTag}
                      </span>

                      <p className="text-sm sm:text-base text-gray-300 font-light leading-relaxed">
                        {archetypeDesc}
                      </p>

                      {/* Total Score Counter */}
                      <div className="pt-2 flex items-baseline gap-3">
                        <span className="text-5xl sm:text-6xl font-black text-white tracking-tight">
                          {totalScore}
                        </span>
                        <span className="text-xl sm:text-2xl text-gray-400 font-mono font-medium">
                          / 100
                        </span>
                      </div>
                    </div>

                    {/* Dynamic SVG Radar Chart */}
                    <div className="md:col-span-5 flex flex-col items-center justify-center p-4 rounded-2xl bg-black/40 border border-white/10 shadow-inner">
                      <RadarChart scores={scores} />
                      <span className="mt-2 text-[10px] font-mono text-gray-400 uppercase tracking-widest">
                        4D Career Positioning Polygon
                      </span>
                    </div>
                  </div>
                </div>

                {/* Strength & Critical Vulnerability Grid */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  {/* Greatest Strength */}
                  <div className="p-6 rounded-3xl bg-white/[0.03] border border-emerald-500/30 backdrop-blur-md">
                    <div className="flex items-center gap-2.5 mb-3 text-emerald-400 font-semibold text-sm font-mono uppercase tracking-wider">
                      <CheckCircle2 className="w-4 h-4" />
                      <span>Your Greatest Strength</span>
                    </div>
                    <div className="text-lg font-bold text-white mb-2">
                      {CATEGORIES.find((c) => c.id === highestCategory)?.title.split(' ')[0]} Fluency
                    </div>
                    <p className="text-xs sm:text-sm text-gray-300 font-light leading-relaxed">
                      {FEEDBACK[highestCategory]}
                    </p>
                  </div>

                  {/* Critical Vulnerability */}
                  <div className="p-6 rounded-3xl bg-white/[0.03] border border-orange-500/30 backdrop-blur-md">
                    <div className="flex items-center gap-2.5 mb-3 text-orange-400 font-semibold text-sm font-mono uppercase tracking-wider">
                      <AlertTriangle className="w-4 h-4" />
                      <span>Critical Vulnerability</span>
                    </div>
                    <div className="text-lg font-bold text-white mb-2">
                      {CATEGORIES.find((c) => c.id === lowestCategory)?.title.split(' ')[0]} Risk
                    </div>
                    <p className="text-xs sm:text-sm text-gray-300 font-light leading-relaxed">
                      {WARNINGS[lowestCategory]}
                    </p>
                  </div>
                </div>

                {/* 4 Dimension Numeric Tally */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  {CATEGORIES.map((cat) => {
                    const sc = scores[cat.id];
                    const pct = Math.round((sc / 25) * 100);
                    return (
                      <div key={cat.id} className="p-4 rounded-2xl bg-white/[0.02] border border-white/[0.08]">
                        <div className="text-[11px] font-mono text-gray-400 uppercase tracking-wider">
                          {cat.title.split(' ')[0]}
                        </div>
                        <div className="text-xl sm:text-2xl font-bold text-white mt-1">
                          {sc} <span className="text-xs text-gray-400 font-normal">/ 25</span>
                        </div>
                        <div className="w-full h-1.5 bg-white/10 rounded-full mt-2 overflow-hidden">
                          <div
                            className="h-full rounded-full transition-all duration-700"
                            style={{ width: `${pct}%`, backgroundColor: cat.themeColor }}
                          />
                        </div>
                      </div>
                    );
                  })}
                </div>

                {/* Action Buttons: Retake, Share, Ecosystem Bridge */}
                <div className="p-6 rounded-3xl bg-white/[0.02] border border-white/[0.08] flex flex-col sm:flex-row items-center justify-between gap-4">
                  <button
                    onClick={handleReset}
                    className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-white/[0.06] hover:bg-white/[0.12] text-gray-200 hover:text-white font-medium text-xs sm:text-sm transition-all cursor-pointer"
                  >
                    <RotateCcw className="w-4 h-4" />
                    <span>Retake Audit</span>
                  </button>

                  <div className="flex items-center gap-3 w-full sm:w-auto">
                    <button
                      onClick={handleShare}
                      className="flex-1 sm:flex-none inline-flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-orange-600 hover:bg-orange-500 text-white font-bold text-xs sm:text-sm transition-all shadow-[0_4px_16px_rgba(234,88,12,0.3)] cursor-pointer"
                    >
                      <Share2 className="w-4 h-4" />
                      <span>{copiedLink ? 'Diagnosis Copied!' : 'Share Your Diagnosis'}</span>
                    </button>

                    <Link
                      to="/join"
                      className="flex-1 sm:flex-none inline-flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-[var(--color-cmf-gold)] hover:bg-[#FFE066] text-black font-bold text-xs sm:text-sm transition-all shadow-[0_4px_16px_rgba(255,204,0,0.3)]"
                    >
                      <span>Join WhatsApp Guild</span>
                      <ArrowRight className="w-4 h-4" />
                    </Link>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* ═════════════════════════════════════════════════════════════════
              AUDIT QUESTIONS FORM (Hidden when calculated, shown otherwise)
              ═════════════════════════════════════════════════════════════════ */}
          {!isCalculated && (
            <div className="space-y-8 sm:space-y-12">
              {CATEGORIES.map((category) => {
                const Icon = category.icon;
                return (
                  <section
                    key={category.id}
                    className="bg-[#0D0D14]/90 rounded-3xl border border-white/10 overflow-hidden backdrop-blur-xl shadow-xl transition-all"
                  >
                    {/* Category Header */}
                    <div className="p-5 sm:p-7 border-b border-white/[0.08] bg-white/[0.02] flex items-start gap-4">
                      <div
                        className="w-10 h-10 rounded-2xl flex items-center justify-center font-bold text-base shrink-0 shadow-md text-white"
                        style={{ backgroundColor: category.themeColor }}
                      >
                        {category.num}
                      </div>
                      <div>
                        <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
                          {category.title}
                        </h2>
                        <p className="mt-1 text-xs sm:text-sm text-gray-400 font-light leading-relaxed">
                          {category.subtitle}
                        </p>
                      </div>
                    </div>

                    {/* Questions List */}
                    <div className="p-5 sm:p-7 space-y-8">
                      {category.questions.map((question, qIdx) => {
                        const qNum = qIdx + 1;
                        const key = `${category.id}_${qIdx}`;
                        const currentVal = answers[key];

                        return (
                          <div key={qIdx} className="space-y-3">
                            <p className="font-semibold text-sm sm:text-base text-gray-200 leading-snug">
                              <span className="font-mono text-orange-400 mr-2">{category.num}.{qNum}</span>
                              {question}
                            </p>

                            {/* 5-Option Likert Scale Buttons */}
                            <div className="grid grid-cols-5 gap-1.5 sm:gap-2.5 pt-1">
                              {SCALES.map((scale) => {
                                const isSelected = currentVal === scale.val;
                                return (
                                  <button
                                    key={scale.val}
                                    type="button"
                                    onClick={() => handleSelectAnswer(category.id, qIdx, scale.val)}
                                    className={`py-3 px-1 sm:py-2.5 sm:px-2 rounded-xl text-center text-xs font-semibold transition-all duration-200 cursor-pointer select-none touch-manipulation border ${
                                      isSelected
                                        ? 'bg-orange-600 text-white border-orange-500 shadow-[0_4px_16px_rgba(234,88,12,0.4)] scale-[1.02]'
                                        : 'bg-white/[0.04] text-gray-400 border-white/[0.08] hover:bg-white/[0.08] hover:text-white hover:border-white/20'
                                    }`}
                                  >
                                    <span className="block truncate">{scale.label}</span>
                                  </button>
                                );
                              })}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </section>
                );
              })}

              {/* ═════════════════════════════════════════════════════════════
                  STICKY BOTTOM PROGRESS BAR & SUBMIT TRIGGER
                  ═════════════════════════════════════════════════════════════ */}
              <div className="sticky bottom-4 sm:bottom-6 z-40 bg-[#0E0E14]/95 backdrop-blur-xl p-4 sm:p-5 rounded-2xl shadow-[0_10px_35px_rgba(0,0,0,0.8)] border border-white/15 flex flex-col sm:flex-row items-center justify-between gap-4">
                
                {/* Progress Indicators */}
                <div className="flex items-center gap-3 w-full sm:w-auto">
                  <div className="w-10 h-10 rounded-full bg-white/[0.05] border border-white/10 flex items-center justify-center font-mono text-xs font-bold text-orange-400 shrink-0">
                    {answeredCount}
                  </div>
                  <div>
                    <div className="text-xs sm:text-sm font-bold text-white">
                      {answeredCount === totalQuestions ? 'All Questions Answered!' : `${answeredCount} of ${totalQuestions} answered`}
                    </div>
                    <div className="w-32 sm:w-44 h-1.5 bg-white/10 rounded-full mt-1 overflow-hidden">
                      <div
                        className="h-full bg-gradient-to-r from-orange-500 to-[var(--color-cmf-gold)] rounded-full transition-all duration-300"
                        style={{ width: `${(answeredCount / totalQuestions) * 100}%` }}
                      />
                    </div>
                  </div>
                </div>

                {/* Calculate Score CTA Button */}
                <button
                  type="button"
                  disabled={!isComplete}
                  onClick={handleCalculate}
                  className={`w-full sm:w-auto py-3.5 px-8 rounded-xl font-bold text-xs sm:text-sm tracking-wide transition-all duration-300 flex items-center justify-center gap-2 ${
                    isComplete
                      ? 'bg-gradient-to-r from-orange-600 via-orange-500 to-amber-500 hover:from-orange-500 hover:to-amber-400 text-white shadow-[0_8px_30px_rgba(234,88,12,0.45)] cursor-pointer active:scale-95 animate-pulse'
                      : 'bg-white/[0.06] text-gray-500 border border-white/10 cursor-not-allowed'
                  }`}
                >
                  <span>Calculate My Score</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          )}

        </div>
      </main>
    </>
  );
}
